URL_API = 'https://qa-challenge-nine.vercel.app/api/name-checker'
REQUEST_LOGS_DATABASE_FILE = "request_logs.db"

EXECUTION_TIME_IN_SECODS = 10
CLEAN_LOGS_BEFORE_EXECUTION = True

ENABLE_THROTTLING_REQUESTS = False
MAX_REQUESTS_PER_SECOND = 3

NAMES_DATABASE_FILE = "names.db"